# Generated by Django 5.2.5 on 2025-08-25 15:33

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.student_profile_upload),
        ),
    ]
